### ISSUE TITLE
Add Null safe version

### ISSUE THREAD

**Issue by aqwert** [wslaimin/http_proxy#2]
This package depends on `http: ^0.12.1`. Please upgrade to null safety and use `http: 0.13.0`

**Comment by zhaopingfu** [comment]
+1

**Comment by zhaopingfu** [comment]
+1

**Comment by zhaopingfu** [comment]
+1

**Comment by aqwert** [comment]
I am getting the feeling this repo is no longer maintained. A number of forks have implemented null safety and now 2 PRs waiting

**Comment by littleGnAl** [comment]
I have[ forked the repository](https://github.com/littleGnAl/http_proxy) and migrated it to null-safety, you can use it by using git reference.

```yaml
http_proxy:
  git: 
    url: https://github.com/littleGnAl/http_proxy.git
```
